services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=automatizacion
      - DB_PORT=3308
      - PORT_APP=3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: automatizacion
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
