# Etapa 1: Clonar repositorio
FROM ubuntu:20.04 AS linux
RUN apt-get update && apt-get install -y git && \
    git clone -b main https://github.com/sxfivglz/Automatizacion /app

# Etapa 2: Construir aplicación
FROM node:20 AS base
WORKDIR /usr/src/app
COPY --from=linux /app /usr/src/app

RUN apt-get update && apt-get install -y gnupg && \
    apt-get install -y mariadb-client && \
    apt-get install -y netcat-openbsd && \
    npm install

RUN apt-get install -y wget
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN apt-get update && apt-get -y install google-chrome-stable
RUN apt-get update && apt-get install -y \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends

# Instalar ChromeDriver
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/ && \
    rm /tmp/chromedriver.zip

# Copiar wait-for-it.sh al contenedor
COPY wait-for-it.sh /usr/src/app/wait-for-it.sh
RUN chmod +x /usr/src/app/wait-for-it.sh


# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando para iniciar la aplicación y ejecutar pruebas
CMD ["/usr/src/app/wait-for-it.sh", "mysql:3306", "--", "npx", "concurrently", "npm start", "npx jest --watchAll"]