version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"