services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=  # Si tienes contraseña para la base de datos, añádela aquí
      - DB_NAME=automatizacion
      - DB_PORT=3306  # Puerto mapeado de MySQL en el host
      - PORT_APP=3000
    ports:
      - "3000:3000"  # Exponer el puerto de la aplicación
    depends_on:
      - mysql
    shm_size: '5gb'
    #entrypoint: [ "npm", "start"]

  mysql:
    image: mariadb:10.5  # Usando la imagen oficial de MariaDB
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''  # Si no estás usando contraseña, dejar vacío
      MYSQL_DATABASE: automatizacion
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3309:3306"  # Mapeo del puerto 3309 del host al 3306 del contenedor de MySQL
    #volumes:
     # - mysql_data:/var/lib/mysql  # Persistir los datos de la base de datos

volumes:
  mysql_data: 
